name: deno-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb://localhost:27017/myaddo
      JWT_KEY_JSON: ${{ secrets.JWT_KEY_JSON }}
      SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
      SEND_GRID_EMAIL: ${{ secrets.SEND_GRID_EMAIL }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
      TWILIO_TEST_NUMBER: ${{ secrets.TWILIO_TEST_NUMBER }}

    steps:
      - uses: actions/checkout@v3

      - name: Install NPM deps
        run: npm i -g wait-on

      - uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.x # Run with latest stable Deno.

      - name: Format & Lint
        run: deno task check

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7.0-rc

      - name: Build
        run: deno task build

      - name: Unit Tests
        run: deno test --allow-all --coverage=cov/

      - name: Start Service
        run: deno run --unstable -A --allow-env --allow-net --allow-read --allow-write ./main.ts & npx wait-on http://127.0.0.1:8000/public/login && echo SUCCESS

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
        id: setup-chrome

      - name: E2E Tests
        run: deno task e2e

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: flexy-fresh
          entrypoint: main.ts
